Revert "update chromeperf deployment for default"
This reverts commit 60758cdaa97644c2ae529f88a688f19b70029d87.

Reason for revert: Found issue in alertgroup:
File "/home/vmagent/app/models/alert_group.py", line 163, in GetGroupsForAnomaly
    g['project_id'] == s.get('monorail_project_id', '') and
KeyError: 'project_id'

Original change's description:
> update chromeperf deployment for default
>
> https://chromium.googlesource.com/catapult.git/+log/a55f4cc..338b5a8
>
> Bug: chromium:1475124
> Change-Id: I468cfc528a2ecdf1ea98a2574e0fbd976c95e3be
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4804427
> Reviewed-by: John Chen <johnchen@chromium.org>
> Commit-Queue: Hao Wu <haowoo@google.com>

Bug: chromium:1475124
Change-Id: I0bb6ab872ea2b6e59161b3c605350aab2ca1d61f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4807139
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: John Chen <johnchen@chromium.org>
Commit-Queue: Wenbin Zhang <wenbinzhang@google.com>