Prevent contention errors in DeleteAsync using existence checks.
This error spiked in the dashboard yesterday, with nearly 8000 occurrences
within 24 hours:
TransactionFailedError: too much contention on these datastore entities. please
try again. entity group key: (app=s~chromeperf, CachedPickledString,
"externally_visible__list_tests_get_tests_v2_redacted")

The stack trace implicated a call to layered_cache.DeleteAsync().
Documentation suggests:
Every attempt to create, update, or delete an entity takes place in the context
of a transaction. There is a write throughput limit of about one transaction per second
within a single entity group.

The stack trace goes on to point to the DeleteAsync call in TestMetadata.CreateCallback.
So it appears that several new master/bot/suite started uploading, creating several
new TestMetadata entities, all of which wanted to purge the CachedPickledString
and MultipartEntity entities containing cached list of tests
for their respective master/bot/suite. However, since the master/bot/suite was
new, it is unlikely that that the CachedPickledString/MultipartEntity entities
existed, neither at first nor for each subsequent attempt to purge them.

This fix avoids attempting to delete the entities if they don't exist. Calling
get() does not automatically create a transaction. This fix should reduce calls
to delete entities, and thereby reduce contention on them.

This cached list of tests is only used by the V1 UI. V2spa uses a different set
of cached test suite descriptors, which is not purged when new TestMetadata
entities are created, so test suite descriptors may be stale for up to a day. That
could change if users complain, in which case this bugfix would benefit v2spa as
well as v1 ui.

Bug: chromium:920304

Change-Id: I9e826590208370f140819e3d94dbe428812c626b
Reviewed-on: https://chromium-review.googlesource.com/c/1403458
Reviewed-by: Sean McCullough <seanmccullough@chromium.org>
Commit-Queue: Ben Hayden <benjhayden@chromium.org>