Revert "Make pydeps files deterministic"
This reverts commit 5eeb59b9e99b1ec1a3bff01581eeed0e7cccd85b.

Reason for revert: Breaks merge script

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\b\s\w\ir\cipd_bin_packages\3.8\bin\Lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\b\s\w\ir\cipd_bin_packages\3.8\bin\Lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\b\s\w\ir\cipd_bin_packages\3.8\bin\Lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\b\s\w\ir\cipd_bin_packages\3.8\bin\Lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\b\s\w\ir\cipd_bin_packages\3.8\bin\Lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\b\s\w\ir\cipd_bin_packages\3.8\bin\Lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\b\s\w\ir\cipd_bin_packages\3.8\bin\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\b\s\w\ir\cache\builder\angle\scripts\process_angle_perf_results.py", line 53, in <module>
    from tracing.value import histogram
  File "C:\b\s\w\ir\cache\builder\angle\third_party\catapult\tracing\tracing\value\histogram.py", line 17, in <module>
    from tracing.proto import histogram_proto
  File "C:\b\s\w\ir\cache\builder\angle\third_party\catapult\tracing\tracing\proto\histogram_proto.py", line 9, in <module>
    if os.path.basename(sys.modules['__main__'].__file__) == 'print_python_deps.py':
AttributeError: module '__main__' has no attribute '__file__'

Original change's description:
> Make pydeps files deterministic
>
> Don't load histogram_pb2 module while calculating Python dependencies,
> to avoid generating nondeterministic pydeps files.
>
> Bug: chromium:1408952
> Change-Id: I85ab8c15e9dc2e7773c6336cccaa3c2bfd6e7e6b
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4183076
> Reviewed-by: Wenbin Zhang <wenbinzhang@google.com>
> Commit-Queue: Wenbin Zhang <wenbinzhang@google.com>
> Auto-Submit: John Chen <johnchen@chromium.org>

Bug: chromium:1408952
Change-Id: I8491b9d30e2ecaa88cf90ca9000108754b90757b
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4188336
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Roman Lavrov <romanl@google.com>
Reviewed-by: Deep Roy <dproy@chromium.org>
Commit-Queue: Deep Roy <dproy@chromium.org>