Revert of Plumb trace canonicalUrl through TelemetryInfo. (patchset #6 id:160001 of https://chromiumcodereview.appspot.com/3007063002/ )
Reason for revert:
Broke perf waterfall. Example stack trace:

Traceback (most recent call last):
  <module> at /b/swarming/w/ir/tools/perf/run_benchmark:26
    sys.exit(main())
  main at /b/swarming/w/ir/tools/perf/run_benchmark:22
    return benchmark_runner.main(config, [trybot_command.Trybot])
  main at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/benchmark_runner.py:352
    return command_instance.Run(options)
  Run at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/benchmark_runner.py:222
    return min(255, self._benchmark().Run(args))
  Run at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/benchmark.py:108
    return story_runner.RunBenchmark(self, finder_options)
  RunBenchmark at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/internal/story_runner.py:355
    results.UploadTraceFilesToCloud()
  UploadTraceFilesToCloud at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/internal/results/page_test_results.py:496
    value.UploadToCloud()
  UploadToCloud at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/value/trace.py:144
    self._upload_bucket, self._remote_path, fh.GetAbsPath())
  Insert at /b/swarming/w/ir/third_party/catapult/common/py_utils/py_utils/cloud_storage.py:378
    _RunCommand(command_and_args)
  _RunCommand at /b/swarming/w/ir/third_party/catapult/common/py_utils/py_utils/cloud_storage.py:153
    raise GetErrorObjectForCloudStorageStderr(stderr)
CloudStorageError: BucketNotFoundException: 404 gs://None bucket does not exist.

Locals:
  args       : ['/b/swarming/w/ir/third_party/catapult/third_party/gsutil/gsutil', 'cp', '/b/swarming/w/it2IK7be/tmpRGMr7K.html', 'gs://None/None']
  gsutil     : <subprocess.Popen object at 0x7f0ff2972dd0>
  gsutil_env : None
  stderr     : 'BucketNotFoundException: 404 gs://None bucket does not exist.\n'
  stdout     : ''

Original issue's description:
> Plumb trace canonicalUrl through TelemetryInfo.
>
> Currently, trace canonical URLs are constructed after serializing the trace.
> This prevents Histogram results from containing the canonical URL.
> This CL constructs trace canonical URLs before serializing the trace so that
> Histograms can contain the canonical URL.
>
> Next CLs:
> - format traceUrls generic-set-spans https://codereview.chromium.org/3008203002
> - add traceUrls to CSVBuilder https://codereview.chromium.org/3005203002
> - plumb traceUrls through ChartJsonConverter
>
> BUG=catapult:#2431
>
> Review-Url: https://chromiumcodereview.appspot.com/3007063002
> Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/8859dc2b7175d2c72a1fb1deebb3a0ca003aaa5b

TBR=simonhatch@chromium.org,benjhayden@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=catapult:#2431

Review-Url: https://chromiumcodereview.appspot.com/3007313002