[chromeperf] fix config and describe tests in api
The fix changed the way how arguments are passed to flask handler. The reasons are:
 - when the arguments are passed in as part of the url, the following error shows up:
   File "/workspace/dashboard/dashboard/common/testing_common.py", line 131, in Post
      return self.testapp.post(path, *args, **kwargs)
    File "/root/.vpython-root/65a7ed/lib/python3.8/site-packages/webtest/app.py", line 371, in post
      return self._gen_request('POST', url, params=params, headers=headers,
    File "/root/.vpython-root/65a7ed/lib/python3.8/site-packages/webtest/app.py", line 752, in _gen_request
      return self.do_request(req, status=status,
    File "/root/.vpython-root/65a7ed/lib/python3.8/site-packages/webtest/app.py", line 649, in do_request
      self._check_status(status, res)
    File "/root/.vpython-root/65a7ed/lib/python3.8/site-packages/webtest/app.py", line 678, in _check_status
      raise AppError(
  webtest.app.AppError: Bad response: 404 NOT FOUND (not 200 OK or 3xx redirect for http://localhost/api/describe%3Ftest_suite=test_suite?test_suite=test_suite)
    When running the same setup in python 2, it passed. The URL is mangled only in python 3.
 - Tried using Curl to call the python 3 version in prod with arguments in URL and it worked.
 - Tried running script locally with Python 3.10 and webtest 2.0.35 (as in .vpython3), it worked.
 - The handler uses flask.request.values to load arguments, which should work for both args and form for POST.

Thus, I'm guessing it is caused by some dependencies on the test toolchain. Passing using params should work for testing purpose. (Ideally, we should test passing the arguments in URL and form in both Py2 and Py3 though)

Bug: chromium:1382247
Change-Id: I8f8ec6314fc684f4ab478c9fc8cbbafaa6b2c642
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4108553
Commit-Queue: Wenbin Zhang <wenbinzhang@google.com>
Reviewed-by: Leina Sun <sunxiaodi@google.com>
Reviewed-by: John Chen <johnchen@chromium.org>