Revert "devil: Check for java on PATH when extracting APKs."
This reverts commit f656d384f7679485375a8dfcabcb9d0feee24555.

Reason for revert: ImportError: cannot import name decorators
https://chromium-swarm.appspot.com/task?id=51c59633cb6fb410

Original change's description:
> devil: Check for java on PATH when extracting APKs.
>
> This should make bundletool.py's errors a little clearer when it tries
> invoking java without a java found on PATH, which we've been running
> into a lot lately.
>
> Bug: chromium:1171590
> Change-Id: I1b9a96bdf18bec0e1449f36bcc6d441c6094333a
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2660449
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Commit-Queue: Ben Pastene <bpastene@chromium.org>

Bug: chromium:1171590
Change-Id: I8e70225f488367f4f058c2c3b3090274d85bb279
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2698064
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Auto-Submit: Ben Pastene <bpastene@chromium.org>