Revert "update chromeperf deployment for upload-processing"
This reverts commit d07cde817126b693363d903d936d89076723c7ea.

Reason for revert:
Seeing error: 'NoneType' object has no attribute 'id'

Original change's description:
> update chromeperf deployment for upload-processing
>
> https://chromium.googlesource.com/catapult.git/+log/0c491f4..1ed7202
>
> Bug: chromium:1509511
> Change-Id: I6e7e37ccba312d2e6fea41e07ae2ebb1a0fd9114
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/5101008
> Reviewed-by: John Chen <johnchen@chromium.org>
> Commit-Queue: Jeff Yoon <jeffyoon@google.com>

Bug: chromium:1509511
Change-Id: I2a2832aa8020c0c42ee6b7e75b07c2d1547bd04f
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/5105141
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Jeff Yoon <jeffyoon@google.com>
Reviewed-by: John Chen <johnchen@chromium.org>
Reviewed-by: Jeff Yoon <jeffyoon@google.com>
Commit-Queue: John Chen <johnchen@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Wenbin Zhang <wenbinzhang@google.com>