Reland of [Telemetry][Wpr] Remove old version of archive info. (patchset #1 id:1 of https://codereview.chromium.org/2725323002/ )
Reason for revert:
Fix landed.

Original issue's description:
> Revert of [Telemetry][Wpr] Remove old version of archive info. (patchset #3 id:40001 of https://codereview.chromium.org/2694843002/ )
>
> Reason for revert:
> Broke catapult autoroller, failing with:
>
>     File "e:\b\swarm_slave\w\irddo0yd\third_party\catapult\telemetry\third_party\mock\mock.py", line 1091, in _dot_lookup
>       __import__(import_path)
>   ImportError: No module named archive_info2
> https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_x64_rel_ng/builds/377472
>
> Original issue's description:
> > [Telemetry][Wpr] Remove old version of archive info.
> >
> > BUG=chromium:618698
> >
> > Review-Url: https://codereview.chromium.org/2694843002
> > Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/7f38bdac42989779f5bd19d5a5acd7eb68f9f371
>
> TBR=nednguyen@google.com,charliea@chromium.org,rnephew@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=chromium:618698
>
> Review-Url: https://codereview.chromium.org/2725323002
> Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/1b305da0d509f4122732296a8581fd8ff48dc4c7

TBR=nednguyen@google.com,charliea@chromium.org,perezju@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:618698

Review-Url: https://codereview.chromium.org/2731753002