Reland "[Telemetry] Refactor expectations code into story_filter.py."
This relands https://chromium-review.googlesource.com/c/catapult/+/1839176
It was reverted by https://chromium-review.googlesource.com/c/catapult/+/1864789
Because it broke system_health_smoke_tests with the error
  Traceback (most recent call last):
    RunBenchmark at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/internal/story_runner.py:439
      max_num_values=benchmark.MAX_NUM_VALUES)
    RunStorySet at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/internal/story_runner.py:234
      results.benchmark_name, platform_tags)
    BuildStoryFilter at /b/swarming/w/ir/third_party/catapult/telemetry/telemetry/story/story_filter.py:58
      cls._expectations.GetBenchmarkExpectationsFromParser(fh.read())
  AttributeError: type object 'StoryFilterFactory' has no attribute '_expectations'

PS1 is the original commit.
PS3 contains the fix.

I also manually verified that stories like
system_health.memory_desktop/browse:media:pinterest:2018
are properly being skipped with these changes
(because expectations.config marks them to be skipped)
and stories like system_health.memory_desktop/browse:media:tumblr:2018
are not skipped (because they are not marked to be skipped in
expectations.config right now).

Bug: chromium:985103
Change-Id: I5f3ce1b07569652b734bd1051667fbed0baabb3d
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/1865026
Auto-Submit: Caleb Rouleau <crouleau@chromium.org>
Commit-Queue: Rakib Hasan <rmhasan@google.com>
Reviewed-by: Rakib Hasan <rmhasan@google.com>