[Catapult] Expand supported browsers with some common flavors
Add the following to FindAllBrowserTypes() in desktop_browser_finder.py:
[ 'release_full_x64', 'release_x86', 'release_full_x86',
'debug_full_x64', 'debug_x86', 'debug_full_x86' ]

These are common gn gen targets used by Edge developers, for example
generated with the following command:

gn gen out\debug_full_x64 "--args=target_cpu = \"x64\" symbol_level = 2
is_debug = true is_component_build = true"

But then when trying to run some performance benchmark, for example:

vpython3 tools/perf/run_benchmark blink_perf.css
--browser-executable=out/release_x64/chrome.exe

it throws this error even when not using the debug_full_x64 executable:

AssertionError: Please add debug_full_x64 to
desktop_browser_finder.FindAllBrowserTypes

The same happens when you replace 'debug_full_x64' with any of the other
browser targets added above. So this change adds those keys to that
dictionary.

Change-Id: I56f8346ea636d041b1a3f85bd2c5f098dcea8dc9
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/6217638
Commit-Queue: Brian Sheedy <bsheedy@chromium.org>
Reviewed-by: Sanket Joshi <sajos@microsoft.com>
Auto-Submit: Fernando Fiori <ffiori@microsoft.com>
Reviewed-by: John Chen <johnchen@chromium.org>
Reviewed-by: Brian Sheedy <bsheedy@chromium.org>