Revert "Fix reinit after failure"
This reverts commit 312f525336d2232b21bb60956fa29f2abe0ed87a.

Reason for revert: Suspect this CL of causing autoroll failures. The autoroll with just this CL in it failed multiple times (https://chromium-review.googlesource.com/c/chromium/src/+/753421, https://chromium-review.googlesource.com/c/chromium/src/+/753528) and the failures are about "ImportError: cannot import name fakes": https://logs.chromium.org/v/?s=chromium%2Fbb%2Ftryserver.chromium.mac%2Fmac_chromium_rel_ng%2F581101%2F%2B%2Frecipes%2Fsteps%2Ftelemetry_gpu_unittests__with_patch_%2F0%2Fstdout

Original change's description:
> Fix reinit after failure
> 
> Bug: chromium:780622
> Change-Id: I3fab7cf609bb73dee4330663c3bb98ff945482bf
> Reviewed-on: https://chromium-review.googlesource.com/749628
> Commit-Queue: Ned Nguyen <nednguyen@google.com>
> Reviewed-by: Ned Nguyen <nednguyen@google.com>
> Reviewed-by: Juan Antonio Navarro Pérez <perezju@chromium.org>

TBR=perezju@chromium.org,nednguyen@google.com

Change-Id: I6e09b561a22039bf9c8747cc2d07a94bfbddf7d2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:780622
Reviewed-on: https://chromium-review.googlesource.com/754046
Reviewed-by: Annie Sullivan <sullivan@chromium.org>
Commit-Queue: Annie Sullivan <sullivan@chromium.org>