Revert "[Fuchsia] Add --output-error=warn for tee to avoid breaking pipe"
This reverts commit 2d01747514cdf81a24a06653706a732f0c7d7c0e.

Reason for revert: It's still failing, likely the accurate way of handling it is to use tee.py (https://crsrc.org/b/recipes/tee.py;l=13?q=tee.py) or other implementations.

Original change's description:
> [Fuchsia] Add --output-error=warn for tee to avoid breaking pipe
>
> It causes issues like
>
>   print_ at /b/s/w/ir/third_party/catapult/third_party/typ/typ/runner.py:196
>     self.host.print_(msg, end, stream=stream)
>   print_ at /b/s/w/ir/third_party/catapult/third_party/typ/typ/host.py:160
>     stream.flush()
> BlockingIOError: [Errno 11] write could not complete without blocking
>
> Due to tee: 'standard output': Resource temporarily unavailable
>
> Bug: chromium:1280703
> Change-Id: Id02dd3692d3a978d6fa5106bebc41f11693f2545
> Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4599837
> Reviewed-by: Brian Sheedy <bsheedy@chromium.org>
> Commit-Queue: Zijie He <zijiehe@google.com>

Bug: chromium:1280703
Change-Id: I5bc65330558c41304f1455bd86b1350d66f7c337
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4692064
Commit-Queue: Zijie He <zijiehe@google.com>
Reviewed-by: Brian Sheedy <bsheedy@chromium.org>