[pinpoint] Copy the files instead of using symlink
The original script generates the deployment folder by creating symbolic links to some folders in the context of docker node. E.g.:
.../src/third_party/catapult/deploy-dashboard/elements -> /workspace/dashboard/dashboard/pinpoint/elements

While it works fine to deploy the yaml in python 2, it sees the following error when deploying the yaml in python 3:
ERROR: gcloud crashed (FileNotFoundError): [Errno 2] No such file or directory: '.../src/third_party/catapult/deploy-dashboard/components'

We can either create a symbolic link from src/third_party/catapult/deploy-dashboard/xxx to src/third_party/catapult/deploy-dashboard/../dashboard/dashboard/pinpoint/xxx
or we can simply do copy.

This CL implements the latter.

Bug: chromium:1241093
Change-Id: If893056e06368fa9afcbcd5975c56aa7f366847d
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3723549
Commit-Queue: Wenbin Zhang <wenbinzhang@google.com>
Reviewed-by: John Chen <johnchen@chromium.org>