Telemetry / Android: do not crash on GetCpuStats() if the process is gone.
Some bots are failing with:
...[0].split()
IndexError: list index out of range
This can specially happen on page cyclers,
since multiple renders can be started and killed by the
framework.

BUG=

Review URL: https://codereview.chromium.org/25002005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@226642 0039d316-1c4b-4281-b951-d872f2087c98