Revert "Configure gae_ts_mon in chromeperf dashboard."
This reverts commit 5e7ddfe4f2b219d3e95a675bf8e09aaa0773d935.

Reason for revert: Dashboard failing with error "ImportError: cannot import name gae_ts_mon"

Bug: 873102

Original change's description:
> Configure gae_ts_mon in chromeperf dashboard.
> 
> This CL configures the chromeperf dashboard to report metrics using gae_ts_mon.
> 
> https://dev-benjhayden-1155789-dot-chromeperf.appspot.com
> 
> Bug: chromium:867060
> Change-Id: I59615f76634bfac5e2da1c813af07923de0fc39c
> Reviewed-on: https://chromium-review.googlesource.com/1155789
> Commit-Queue: Ben Hayden <benjhayden@chromium.org>
> Reviewed-by: Annie Sullivan <sullivan@chromium.org>

TBR=sullivan@chromium.org,benjhayden@chromium.org,seanmccullough@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: chromium:867060
Change-Id: I5dd977f13be9bdf96d165d9252e6174f4bee5ef0
Reviewed-on: https://chromium-review.googlesource.com/1170043
Reviewed-by: Annie Sullivan <sullivan@chromium.org>
Commit-Queue: Annie Sullivan <sullivan@chromium.org>