Reland of [Telemetry] Remove the logic of killing stray adb processes (patchset #1 id:1 of https://codereview.chromium.org/2487493002/ )
Reason for revert:
Didn't fix the issue.

Original issue's description:
> Revert of [Telemetry] Remove the logic of killing stray adb processes (patchset #1 id:1 of https://codereview.chromium.org/2424843002/ )
>
> Reason for revert:
> Looks like this is causing errors when landing in chrome.
> From https://codereview.chromium.org/2477243003
>
>
> A revert of this CL (patchset #1 id:1) has been created in
> https://codereview.chromium.org/2484833002/ by scheib@chromium.org.
>
> The reason for reverting is: Failed compile on official.desktop.continuous for
> win trunk
> https://bugs.chromium.org/p/chromium/issues/detail?id=662998
>
> Link to Build:
> -------------
> https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/w...
>
> Link to Log Path:
> ------------------
> https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/w...
>
> Error log :
>
> FAILED: net_unittests.exe net_unittests.exe.pdb
> C:/b/depot_tools/python276_bin/python.exe
> ../../build/toolchain/win/tool_wrapper.py link-wrapper environment.x64 False
> link.exe /nologo /OUT:./net_unittests.exe /PDB:./net_unittests.exe.pdb
> @./net_unittests.exe.rsp
> c:\b\build\slave\win_trunk\build\src\v8\src\heap\mark-compact.cc(1278) : fatal
> error C1001: An internal error has occurred in the compiler.
> (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 255)
>  To work around this problem, try simplifying or changing the program near the
> locations listed above.
> Please choose the Technical Support command on the Visual C++
>  Help menu, or open the Technical Support help file for more information
>
>
> scheib@ could you please look into this. thank you
>
> Original issue's description:
> > [Telemetry] Remove the logic of killing stray adb processes
> >
> > This was a hack to provide a bandaid fix for crbug.com/656224.
> >
> >
> > BUG=chromium:656224
> >
> > Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/0adb6ef9b5dd024442c143933dd58d946f0f9bac
>
> TBR=jbudorick@chromium.org,eyaich@chromium.org,nednguyen@google.com
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=chromium:656224
>
> Committed: https://chromium.googlesource.com/external/github.com/catapult-project/catapult/+/d18e525a0681b1add863ed672fcea573cf1db68f

TBR=jbudorick@chromium.org,eyaich@chromium.org,nednguyen@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:656224

Review-Url: https://codereview.chromium.org/2487743002