[tracing] Change the algorithm of building sub slices to an iterative algorithm
For a deeply nested trace, (like the one in
https://github.com/catapult-project/catapult/issues/2813#issue-177559995), this speeds
up the importing time by a lot & does not have the stackoverflow problem.

Before:
time ./tracing/bin/run_metric tracing/test_data/trace.json sampleMetric
[ RUN      ] /usr/local/google/home/nednguyen/projects/catapult/tracing/test_data/trace.json
TraceImportError: Maximum call stack size exceeded
    at Object.roundedLess (/tracing/base/time_display_modes.html:21:26)
    at Object.bounds (/tracing/model/timed_event.html:52:44)
    at addSliceIfBounds (/tracing/model/slice_group.html:413:18)
    at addSliceIfBounds (/tracing/model/slice_group.html:415:17)
    at addSliceIfBounds (/tracing/model/slice_group.html:415:17)
    at addSliceIfBounds (/tracing/model/slice_group.html:415:17)
    at addSliceIfBounds (/tracing/model/slice_group.html:415:17)
    at addSliceIfBounds (/tracing/model/slice_group.html:415:17)
    at addSliceIfBounds (/tracing/model/slice_group.html:415:17)
    at addSliceIfBounds (/tracing/model/slice_group.html:415:17)
[  FAILED  ] /usr/local/google/home/nednguyen/projects/catapult/tracing/test_data/trace.json (10748 ms)

After:
time ./tracing/bin/run_metric tracing/test_data/trace.json sampleMetric
[ RUN      ] /usr/local/google/home/nednguyen/projects/catapult/tracing/test_data/trace.json
[       OK ] /usr/local/google/home/nednguyen/projects/catapult/tracing/test_data/trace.json (3154 ms)
HTML result created in file:///usr/local/google/home/nednguyen/projects/catapult/results2.html

BUG=catapult:#2813

Review-Url: https://codereview.chromium.org/2366933002