Fix adb install-multiple workaround
On the old adb tool workaround from
https://chromium-review.googlesource.com/c/catapult/+/3452546
doesn't work.
For example, on adb with version 28.0.1 we'll get following error:

java.lang.IllegalArgumentException: Unknown option
--unused-arg-workaround

Removing double-dash fixes this problem.

Change-Id: Ib422c354dac3b99e14a3d29dcf72d34f39f8b032
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3593232
Auto-Submit: Victor Samun <victorsamun@yandex-team.ru>
Reviewed-by: Peter Wen <wnwen@chromium.org>
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>